In [1]:
import numpy as np

In [2]:
my_list = [10,20,30]

In [4]:
#numpy'da diziler vardır. liste gibidir, ancak numpyin kuralları daha farklı.

In [3]:
type(my_list)

list

In [5]:
np.array(my_list)

array([10, 20, 30])

In [6]:
my_array = np.array(my_list)

In [7]:
type(my_array)

numpy.ndarray

In [8]:
my_array.max()

30

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.random.random(6)

array([0.06418079, 0.7691091 , 0.16014808, 0.9039491 , 0.21030732,
       0.16607623])

In [30]:
# dizi aritmetiği

In [20]:
data = np.arange(0,6,1)

In [21]:
data

array([0, 1, 2, 3, 4, 5])

In [27]:
ones = np.ones(6)

In [28]:
ones

array([1., 1., 1., 1., 1., 1.])

In [31]:
data + ones #broadcast

array([1., 2., 3., 4., 5., 6.])

In [32]:
# arange and indexing

In [33]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [34]:
list(range(0,5,2))

[0, 2, 4]

In [36]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(0,5,2)

array([0, 2, 4])

In [42]:
np_array = np.arange(0,10,2)

In [43]:
np_array

array([0, 2, 4, 6, 8])

In [45]:
np_array[3]

6

In [46]:
np_array[-1]

8

In [47]:
np_array[1:3]

array([2, 4])

In [48]:
#random

In [52]:
matrix_test = np.random.randn(5,5)

In [54]:
matrix_test

array([[ 0.36989435,  0.33409818, -0.34654452,  0.06643225,  0.74071401],
       [-0.67976046, -0.28106566,  0.18219846,  0.82760621, -1.16325165],
       [-0.60909093, -0.93634975, -1.09840448, -0.29518664,  0.25592284],
       [-1.71419223,  0.28167527, -0.25919158, -1.18574436, -1.06475152],
       [ 0.64114611, -1.28221165,  0.99310576,  0.24711337,  0.49655039]])

In [57]:
matrix_test[0:2]

array([[ 0.36989435,  0.33409818, -0.34654452,  0.06643225,  0.74071401],
       [-0.67976046, -0.28106566,  0.18219846,  0.82760621, -1.16325165]])

In [51]:
np.random.randint(1,100,5)

array([15, 54,  3, 35, 96])

In [85]:
float_matrix1 = np.random.uniform(0,100, size = (2,2))

In [86]:
float_matrix1

array([[41.37069374, 55.50672745],
       [25.32601435, 20.53005715]])

In [87]:
float_matrix2 = np.random.uniform(0,100, size = (2,2))

In [88]:
float_matrix2

array([[10.80073116, 90.43749177],
       [81.78865685, 44.62221773]])

In [89]:
float_matrix1*float_matrix2

array([[ 446.83374099, 5019.88920655],
       [2071.38069738,  916.09668017]])