In [1]:
import numpy as np

In [3]:
first_array = np.array([[10,20],[30,40]])

In [4]:
second_array = np.array([[5,15],[25,35]])

In [5]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [6]:
third_array = np.array([[50,60]])

In [7]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [9]:
fourth_array = np.array([[10],[20]])

In [10]:
fourth_array.shape

(2, 1)

In [12]:
first_array.shape

(2, 2)

In [13]:
first_array

array([[10, 20],
       [30, 40]])

In [15]:
fourth_array

array([[10],
       [20]])

In [16]:
first_array + fourth_array

array([[20, 30],
       [50, 60]])

In [17]:
# matrix multiplication

In [18]:
first_array

array([[10, 20],
       [30, 40]])

In [19]:
second_array

array([[ 5, 15],
       [25, 35]])

In [21]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [22]:
# dot product

In [24]:
first_matrix = np.array([[10,20,30]])

In [25]:
first_matrix.shape

(1, 3)

In [26]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [27]:
second_matrix.shape

(3, 2)

In [28]:
first_matrix.dot(second_matrix)

array([[120, 180]])

In [37]:
third_matrix = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])

In [38]:
third_matrix.shape

(4, 4)

In [41]:
fourth_matrix = np.array([[1,2],[1,2],[1,2],[1,2]])

In [42]:
fourth_matrix.shape

(4, 2)

In [43]:
third_matrix.dot(fourth_matrix)

array([[10, 20],
       [10, 20],
       [10, 20],
       [10, 20]])