In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([ 5, 96, 82, 75, 98,  9, 68, 28, 82, 76,  9, 73, 83, 55, 78, 44,  6,
       19, 18, 32])

In [4]:
new_array > 25

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
       False,  True])

In [5]:
new_array[new_array > 25]

array([96, 82, 75, 98, 68, 28, 82, 76, 73, 83, 55, 78, 44, 32])

In [6]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [7]:
matrix_array.shape

(3, 2)

In [9]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [8]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [17]:
random_array = np.random.uniform(0,100,size = (6,1))

In [18]:
random_array

array([[26.75311701],
       [77.27350342],
       [80.0855607 ],
       [26.13650858],
       [29.04741167],
       [ 6.05677653]])

In [20]:
random_array.shape

(6, 1)

In [21]:
random_array.reshape(2,3)

array([[26.75311701, 77.27350342, 80.0855607 ],
       [26.13650858, 29.04741167,  6.05677653]])

In [22]:
random_array.reshape(3,2)

array([[26.75311701, 77.27350342],
       [80.0855607 , 26.13650858],
       [29.04741167,  6.05677653]])