In [ ]:
 # Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100, counting by 10?



In [2]:
import numpy as np

In [6]:
first_array = np.arange(10,110,10)

In [7]:
first_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
# How could you create the same NumPy array using a Python range and a list?

In [9]:
np.array([i for i in range(10,110,10)])

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
# How would you create a ten-element NumPy array object of all zeros


In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# How could you create a ten-element array of random integers between 1 and 5 (inclusive)?



In [14]:
np.random.randint(1,6,10)

array([4, 2, 3, 4, 2, 2, 1, 1, 4, 5])

In [17]:
# # np.random.randfloat(1,6,10)

In [20]:
np.random.rand(10)

array([6.91230556e-01, 8.28871081e-04, 1.41975585e-01, 1.49138888e-01,
       4.66660585e-01, 4.84523270e-01, 1.32203706e-01, 2.66666007e-01,
       5.61114635e-01, 9.25804034e-01])